### ISSUE TITLE
Add Goalie Stats 

### ISSUE THREAD

**Issue by Untuxed** [Untuxed/HockeyBot#11]
Sorry Karl for this oversight, we did not think about goalie stats. Whoever wants to accomplish this I would be thankful

**Comment by Untuxed** [comment]
Interesting concept. Should goalies be stored differently than skaters because their stats are different?

**Comment by Untuxed** [comment]
Another thought We can use the same sheets page, Just shift goalies to the right a bit  and whenever someone calls /get-my-stats it looks through those two tables separately. Theoretically, Karl could show up in both a skater stat and goalie stat. 

Now that we have these issues I decided to use them instead of blowing up the dev channel on discord

**Comment by KOhaus94** [comment]
> Interesting concept. Should goalies be stored differently than skaters because their stats are different?

There is a chance a goalie gets a traditional stat (goal, assist, PIMs, etc.)
Do the discord interactions check for role? We could say if role == goalie, generate a different stats message.

**Comment by KOhaus94** [comment]
Goalie stats we could track (ignoring annoying counting stats like SA, GA, SVs, and SV%): GP, W, L, OTL. GA/G. SO, Shootout Shots Against, Shootout Saves, Shootout Save Percentage
